name: pelo
description: Track Bike Metrics

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  scoped_model: ^1.0.1
  oauth2: ^1.2.3
  http: ^0.12.0+1
  webview_flutter: ^0.2.0
  url_launcher: ^4.0.3
  uni_links: ^0.1.4
  path_provider: ^0.4.1
  flutter_blue: ^0.4.2
  flutter_webview_plugin: ^0.3.0+2
  uuid: any
  http_parser: ^3.1.3
  video_player: ^0.7.2
  shared_preferences: ^0.4.3
  json_annotation: ^2.0.0
  simple_permissions: ^0.1.9
  cached_network_image: ^0.6.0-alpha.2
  flutter_cache_manager: ^0.3.0-alpha.2
  intl: any

dev_dependencies:
  json_serializable: ^2.0.0
  build_runner: ^1.0.0

  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/dog.jpg
    - assets/food.jpg
    - assets/background.jpg
    - assets/strava_logo_orange.png
    - assets/strava_symbol_orange.png
    - assets/peloton.png
    - assets/peloton_banner.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
